on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint -- --max-warnings 0
      - name: Fail on errors
        run: |
          if [ -n "$(git status --porcelain | grep -v '^??')" ]; then
            echo "ESLint found errors, please fix them and try again."
            git status
            exit 1
          fi
